# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0002_subreddit_popularity'),
        ('post', '0002_post_num_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subreddit',
        ),
        migrations.AddField(
            model_name='post',
            name='subreddits',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='subreddit.Subreddit'),
        ),
    ]
