# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
